name: CI

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  uji:
    name: Uji Unit (node:test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pasang Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Jalankan Unit Test
        run: npm test

  lint:
    name: Linting Markup (html-validate)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pasang Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Validasi HTML
        run: npx --yes html-validate index.html
